kind: Deployment
apiVersion: apps/v1
metadata:
 name: backend-deployment
 namespace: app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: backend-app
 template:
  metadata:
   name: backend-pod
   labels:
    app: backend-app
  spec:
   containers:
   - name: backend-container
     image: vinayak100ni/chat-app-k8s-backend:latest
     ports:
     - containerPort: 5001
     env:
     - name: NODE_ENV
       value: production
     - name: MONGODB_URI
       value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
     - name: JWT_SECRET
       valueFrom:
        secretKeyRef: 
         name: secret
         key: jwt
     - name: PORT
       value: "5001"

