kind: PersistentVolume
apiVersion: v1
metadata:
 name: pv-mongo
 namespace: app
 labels:
  app: chat-app
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-storage
 hostPath:
  path: /data
